branch-defaults:
  default:
    environment: api-app-env
    group_suffix: null
environment-defaults:
  apiingest-env:
    branch: null
    repository: null
global:
  application_name: api-app
  branch: null
  default_ec2_keyname: null
  default_platform: python3.4
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: null
